version: '2.1'

services:

#  zipkin:
#    build: microservices/support/zipkin-server
#    restart: always
#    ports:
#      - "9411:9411"
#    environment:
#      - MY_CONFIG_USER=${MY_CONFIG_USER}
#      - MY_CONFIG_PWD=${MY_CONFIG_PWD}
#      - JAVA_TOOL_OPTIONS=${MY_JAVA_TOOL_OPTIONS}
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  mongodb:
    image: mongo:3.2.4
    restart: always
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=revDb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
#      test: ["CMD", "mysql", "--user=root", "--password=rootpwd", "-e", "'select 1'"]
#      test: ["CMD", "sleep 10"]
      test: ["CMD", "ls"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: mysqld --max_connections=450

  pro:
    build: microservices/core/product-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=development,docker
      - MY_CONFIG_USER=${MY_CONFIG_USER}
      - MY_CONFIG_PWD=${MY_CONFIG_PWD}
      - JAVA_TOOL_OPTIONS=${MY_JAVA_TOOL_OPTIONS}

  rec:
    build: microservices/core/recommendation-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=development,docker
      - MY_CONFIG_USER=${MY_CONFIG_USER}
      - MY_CONFIG_PWD=${MY_CONFIG_PWD}
      - JAVA_TOOL_OPTIONS=${MY_JAVA_TOOL_OPTIONS}

  rev:
    build: microservices/core/review-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=development,docker
      - MY_CONFIG_USER=${MY_CONFIG_USER}
      - MY_CONFIG_PWD=${MY_CONFIG_PWD}
      - JAVA_TOOL_OPTIONS=${MY_JAVA_TOOL_OPTIONS}

  composite:
    build: microservices/composite/product-composite-service
    restart: always
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development,docker
      - MY_CONFIG_USER=${MY_CONFIG_USER}
      - MY_CONFIG_PWD=${MY_CONFIG_PWD}
      - JAVA_TOOL_OPTIONS=${MY_JAVA_TOOL_OPTIONS}
