apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
        image-tag: "3.2.4"
    spec:
      containers:
        - name: mongodb
          image: mongo:3.2.4
          command: ["mongod"]
          args: ["--smallfiles"]
          ports:
            - containerPort: 27017
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
#  type: ClusterIP
  type: NodePort
  selector:
    app: mongodb-app
  ports:
#  - port: 27017
#    targetPort: 27017
  - name: http
    port: 27017
    targetPort: 27017
    nodePort: 30017

