apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: product-composite
  labels:
    app: product-composite-service
    image-tag: "Spring5-1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-composite-service
  template:
    metadata:
      labels:
        app: product-composite-service
        image-tag: "Spring5-1.0.0"
    spec:
      containers:
      - name: product-composite
        image: magnuslarsson/ms-blog-product-composite-service:Spring5-1.0.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "development,docker"
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx256M"
          - name: MY_CONFIG_USER
            value: "config_client"
          - name: MY_CONFIG_PWD
            value: "config_client_pwd"
        ports:
        - name: https
          containerPort: 8080
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: "/application/info"
            port: 8080
          initialDelaySeconds: 600
          periodSeconds: 60
          timeoutSeconds: 1
---

apiVersion: v1
kind: Service
metadata:
  name: product-composite
spec:
#  type: ClusterIP
  type: NodePort
  selector:
    app: product-composite-service
  ports:
#    - port: 8080
#      targetPort: 8080
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
