apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation-service
    image-tag: "Spring5-1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
        image-tag: "Spring5-1.0.0"
    spec:
      containers:
      - name: recommendation
        image: magnuslarsson/ms-blog-recommendation-service:Spring5-1.0.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "development,docker"
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx256M"
          - name: MY_CONFIG_USER
            value: "config_client"
          - name: MY_CONFIG_PWD
            value: "config_client_pwd"
        ports:
        - name: https
          containerPort: 8080
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: "/application/info"
            port: 8080
          initialDelaySeconds: 600
          periodSeconds: 60
          timeoutSeconds: 1
---

apiVersion: v1
kind: Service
metadata:
#  name: recommendation
  name: rec
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - port: 8080
      targetPort: 8080
