endpoints.sensitive: false

spring.datasource:
  url: jdbc:mysql://localhost/revDb?useSSL=false
  username: user
  password: pwdx
  tomcat:
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: /* ping */ SELECT 1
  hikari:
    leak-detection-threshold: 20000
    minimum-idle: 50
    maximum-pool-size: 400


spring.jpa.database: MYSQL
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create

---
# For deployment in Docker containers
spring:
  profiles: docker

  datasource.url: jdbc:mysql://mysql/revDb?useSSL=false
  rabbitmq.host: rabbitmq

server.port: 8080

---
# For development
spring:
  profiles: development

  cloud.discovery.enabled: false

  rabbitmq.host: localhost

# 1.0 means 100%, see http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sampling
spring.sleuth.sampler.percentage: 1.0

logging:
  level:
    root: INFO
    se.callista: WARN
    org.springframework.data: INFO

server.port: 8083

