endpoints.sensitive: false

---
# For deployment in Docker containers
spring:
  profiles: docker

  rabbitmq.host: rabbitmq

server.port: 8080

product-service.ribbon.listOfServers: pro:8080
recommendation-service.ribbon.listOfServers: rec:8080
review-service.ribbon.listOfServers: rev:8080

---
# For development
spring:
  profiles: development

  cloud.discovery.enabled: false

  rabbitmq.host: localhost

# 1.0 means 100%, see http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sampling
spring.sleuth.sampler.percentage: 1.0

logging:
  level:
    root: INFO
    se.callista: WARN

server.port: 8084

security.ignored: /**

ribbon.eureka.enabled: false

product-service.ribbon.listOfServers: localhost:8081
recommendation-service.ribbon.listOfServers: localhost:8082
review-service.ribbon.listOfServers: localhost:8083

hystrix:
  threadpool:
    default:
      # This property allows the configuration for maximumSize to take effect.  (Default: false)
      allowMaximumSizeToDivergeFromCoreSize: true
      # This is the maximum amount of concurrency that can be supported without starting to reject HystrixCommands.  (Default: 10)
      maximumSize: 400
      # This property sets the core thread-pool size. (Default: 10)
      coreSize: 10
      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: -1
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 3
      execution:
        isolation:
#          strategy: SEMAPHORE, no thread pool but timeout handling stops to work
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
